site_name: System Programming
site_url: https://james-willett.github.io/mkdocs-material-youtube-tutorial/
# theme:
#   name: material
#   features:
#     - navigation.tabs
#     - navigation.sections
#     - toc.integrate
#     - navigation.top
#     - search.suggest
#     - search.highlight
#     - content.tabs.link
#     - content.code.annotation
#     - content.code.copy
#   language: en
#   palette:
#     - scheme: default
#       toggle:
#         icon: material/toggle-switch-off-outline 
#         name: Switch to dark mode
#       primary: teal
#       accent: purple 
#     - scheme: slate 
#       toggle:
#         icon: material/toggle-switch
#         name: Switch to light mode    
#       primary: teal
#       accent: lime

theme:
  name: material
  #custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  #favicon: assets/favicon.png
  icon:
    logo: logo

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/james-willett
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2023 <a href="https://www.linkedin.com/in/soham-kadam-72309115a/"  target="_blank" rel="noopener">Soham Kadam</a>